title: ab-Makes
description: > # this means to ignore newlines until "baseurl:"
  A showcase of projects developed by ab-Makes.  These are mostly Arduino MIDI controllers.
  There are also some arduino/esp8266 projects.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ab-makes.uk" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: ab-Makes
author-img: logo.svg
about-author: Developing Arduino and MIDI devices.  Usually aimed at an individuals requirements, but always usable by many.
social-twitter: aburnsni
social-facebook:
social-github: aburnsni
social-linkedin: aburnsni
social-email: aburnsni@gmail.com

# Disqus
discus-identifier: ab-makes # add your discus identifier

# Tracker
analytics: UA-121802454-1

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

highlighter: rouge

sass:
    sass_dir: assets/css/scss/

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
